=== ElGeras90/centerdivisa/backend-cc/schemas/de1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:de1="http://www.uif.shcp.gob.mx/recepcion/de1"
            targetNamespace="http://www.uif.shcp.gob.mx/recepcion/de1"
	    elementFormDefault="qualified">

    <xsd:element name="reporte" type="de1:reporte_type"></xsd:element>
<!-- ComplexType    -->
    <xsd:complexType name="reporte_type">
        <xsd:sequence>
            <xsd:element name="trimestre_reportado" type="de1:trimestre_type"></xsd:element>
            <xsd:element name="clave_organo_supervisor" type="de1:clave_os_type"></xsd:element>
            <xsd:element name="clave_sujeto" type="de1:clave_sujeto_type"></xsd:element>
            <xsd:element name="modificatorio" type="de1:modificatorio_type" minOccurs="0"></xsd:element>
            <xsd:element name="codigo_postal" type="de1:cp_type" minOccurs="0"></xsd:element>
            <xsd:element name="operacion" type="de1:operacion_type" maxOccurs="unbounded" minOccurs="0"></xsd:element>
            <xsd:element name="contraparte_opero" type="de1:contraparte_opero_type" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="operacion_type">
        <xsd:sequence>
            <xsd:element name="moneda" type="de1:moneda_type"></xsd:element>
            <xsd:element name="numero_operaciones_compra" type="de1:numero_oper_type"></xsd:element>
            <xsd:element name="monto_compra" type="de1:monto_type"></xsd:element>
            <xsd:element name="numero_operaciones_venta" type="de1:numero_oper_type"></xsd:element>
            <xsd:element name="monto_venta" type="de1:monto_type"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="contraparte_opero_type">
        <xsd:sequence>
            <xsd:element name="tipo_contraparte" type="de1:tipo_contraparte_type"></xsd:element>
            <xsd:element name="moneda_operada" type="de1:moneda_type"></xsd:element>
            <xsd:element name="monto_operado_compra" type="de1:monto_type" minOccurs="0"></xsd:element>
            <xsd:element name="monto_operado_venta" type="de1:monto_type" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tipo_contraparte_type">
        <xsd:choice>
            <xsd:element name="nacional" type="de1:nacional_type" minOccurs="0"></xsd:element>
            <xsd:element name="extranjera" type="de1:extranjera_type" minOccurs="0"></xsd:element>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="nacional_type">
        <xsd:sequence>
            <xsd:element name="clave_contraparte" type="de1:clave_contraparte_type"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="extranjera_type">
        <xsd:sequence>
            <xsd:element name="nombre_contraparte" type="de1:nombre_contraparte_type"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
                
<!-- SimpleType -->
    <xsd:simpleType name="clave_contraparte_type">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0]\d{2}(\d{3}|\d{5})"/>
            <xsd:minLength value="6"/>
            <xsd:maxLength value="8"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="clave_os_type">
        <xsd:restriction base="xsd:string">
                <xsd:pattern value="\d{2}-\d{3}"/>
            <xsd:length value="6"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="clave_sujeto_type">
        <xsd:restriction base="xsd:string">
                <xsd:pattern value="[0]\d{7}"/>
            <xsd:length value="8"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="cp_type">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{5}"/>
            <xsd:length value="5"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="nombre_contraparte_type">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-ZÃ‘\d \-\.,&apos;:/#&amp;]{1,200}"/>
            <xsd:minLength value="1"/>
            <xsd:maxLength value="200"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="numero_oper_type">
        <xsd:restriction base="xsd:integer">
            <xsd:pattern value="\d{1,9}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="moneda_type">
        <xsd:restriction base="xsd:string">
                <xsd:pattern value="[A-Z]{3}"/>
            </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="monto_type">
        <xsd:restriction base="xsd:decimal">
            <xsd:pattern value="\d{1,14}\.\d{2}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="trimestre_type">
        <xsd:restriction base="xsd:string">
                <xsd:pattern value="(19|2[0-9])[0-9]{2}\-[1234]"/>
            <xsd:length value="6"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="modificatorio_type">
        <xsd:restriction base="xsd:integer">
            <xsd:pattern value="1"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== ElGeras90/centerdivisa/backend-cc/exports/reporte_de1_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<reporte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uif.shcp.gob.mx/recepcion/de1 de1.xsd" xmlns="http://www.uif.shcp.gob.mx/recepcion/de1">
  <trimestre_reportado>4</trimestre_reportado>
  <clave_organo_supervisor>CNBV</clave_organo_supervisor>
  <clave_sujeto>123456</clave_sujeto>
  <codigo_postal>20000</codigo_postal>
  <operacion>
    <moneda>USD</moneda>
    <numero_operaciones_compra>5</numero_operaciones_compra>
    <monto_compra>368499.00</monto_compra>
    <numero_operaciones_venta>0</numero_operaciones_venta>
    <monto_venta>0.00</monto_venta>
  </operacion>
</reporte>
